Settings:
  # Time before a player starts smelling in seconds
  Time-Before-Smelling: 600
  Stink-Message:
    Enabled: true
    Message: "You stink! Take a bath!"
  Stink-Message-Other:
    Enabled: true
    Message: "%player% near you hasn't taken a bath, it's making you nauseous!"